#!/bin/bash
# Roman Frank, 2014
# 2akellaw@gmail.com

echo -n "Enter name user for new host: "
read newUser

echo -n "Enter name create host: "
read newHost

#Create user $newUser
adduser $newUser

path=/home/${newUser}

echo "New entry in hosts"
file="/etc/hosts"
b=$(cat $file)
newContent="127.0.0.1 ${newHost}"$'\n'"127.0.0.1 www.${newHost}"$'\n'$b
sudo bash -c "echo '${newContent}' > $file"

echo "Creating a file in sites-available"
sap=/etc/apache2/sites-available/$newHost.conf
sudo touch $sap
sudo chmod 777 $sap
directives="
<VirtualHost *:80>
	ServerName ${newHost}
	ServerAlias ${newHost} www.${newHost}
	DocumentRoot ${path}/public_html
	<Directory ${path}/public_html/>
		AllowOverride All
		Require all granted
	</Directory>
	ErrorLog /home/${newUser}/logs/error.log
    CustomLog /home/${newUser}/logs/access.log combined
</VirtualHost>"

echo "$directives" > $sap

echo "Create folders"
mkdir ${path}/public_html
mkdir ${path}/logs
chmod 0777 ${path}/logs

touch ${path}/public_html/index.html

#Enable virtual host
sudo a2ensite $newHost

#Enable mod rewrite"
sudo a2enmod rewrite

#Reboot apache
sudo /etc/init.d/apache2 restart
